export const SET_HARNESS_LIST = 'SET_HARNESS_LIST';
export const SET_XCODE_LIST = 'SET_XCODE_LIST';
export const ACTION_BUTTON_PRESSED = 'ACTION_BUTTON_PRESSED';
export const SET_DEFAULT_XCODE = 'SET_DEFAULT_XCODE';